export type {
    Block_About as IBlock_About,
    Block_Jobs as IBlock_Jobs,
    Block_Projects as IBlock_Projects,
    Block_Repositories as IBlock_Repositories,
    Block_Contact as IBlock_Contact,
    Footer as IFooter,
    Hero as IHero,
    Job as IJob,
    Layout_Primary as ILayout,
    MainLayoutcontentUnion as ILayoutContentItem,
    Maybe,
    Navigation as INavigation,
    Page,
    Project as IProject,
    Seo as ISEO,
} from "../utils/codegen/graphql";
