export type {
    Block_About as IBlock_About,
    Block_Contact as IBlock_Contact,
    Block_Jobs as IBlock_Jobs,
    Block_Projects as IBlock_Projects,
    Block_Projects_IOs as IBlock_Projects_iOS,
    Block_Repositories as IBlock_Repositories,
    Footer as IFooter,
    Hero as IHero,
    Job as IJob,
    Layout_Primary as ILayout,
    Layout_PrimarycontentUnion as ILayoutContentItem,
    Navigation as INavigation,
    Project as IProject,
    Seo as ISEO,
    Maybe,
    Page,
} from "../utils/codegen/graphql";
